language: python

addons:
  apt:
    packages:
    - swig
    - libssl-dev
    - libssl1.0.0
    - python-setuptools
    - python-twisted

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
matrix:
  include:
     - os: osx
       language: generic
  allow_failures:
    - python: "nightly"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install openssl; fi

install:
  - travis_retry pip install Twisted
  - python setup.py install

script: python setup.py test
